version: "3.8"

services:
  backend:
    build:
      context: ./animal-crud # root backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=animal_db

  frontend:
    build:
      context: ./animal-crud-frontend # root frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: animal_db
    ports:
      - "5432:5432"
